services:
  postgres:
    image: postgres:16
    container_name: roomify-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: roomify
      POSTGRES_USER: roomify_user
      POSTGRES_PASSWORD: roomify_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - roomify-network

networks:
  roomify-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
